### PR TITLE
Pause rendering when entering background

### LINKED ISSUE #978: Purple rectangle layer after a background
## Environment

- Xcode version: 13.2
- iOS version: 15.2
- Devices affected: iPhone 13 pro
- Maps SDK Version: 10.2

## Observed behavior and steps to reproduce

After awhile in the background, when I put back the app in foreground. All layers are represented with purple rectangle.
I got the same behavior in the latest mapbox navigation

## Expected behavior

My annotations should be back

287A6EC2-600B-4808-911C-91F48D8D090C

### PR DESCRIPTION
**Pull request by evil159**
`MapView` will now listen to either `UIApplication` or `UIScene` lifecycle event notifications(depending on project setup). As application/scene moves to background/foreground, map view's `displayLink` will be paused/resumed accordingly. 

On iOS 11 and 12 `UIApplication` is the only source of these events. Starting from iOS 13 Scene API can be enabled by including [UIApplicationSceneManifest](https://developer.apple.com/documentation/bundleresources/information_property_list/uiapplicationscenemanifest) key to `Info.plist`. 

Additionally this PR adds `reduceMemoryUse()` call when transitioning to background as its documentation advises.

Fixes #978, #1053 

## Pull request checklist:
 - [x] Write tests for all new functionality. If tests were not written, please explain why.
 - [x] Describe the changes in this PR, especially public API changes.
 - [x] Add a changelog entry to to bottom of the relevant section (typically the `## main` heading near the top).
 - [x] Review and agree to the Contributor License Agreement ([CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement)).

### CODE REVIEW

File: Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import UIKit
+
+@available(iOS 13.0, *)
+extension UIWindow {
+    internal var parentScene: UIScene? {
+        // falling back to ``CPWindow.templateApplicationScene`` to also cover CarPlay
+        return windowScene ?? self.value(forKeyPath: "templateApplicationScene") as? UIScene
```
Comment (evil159) [inline Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift:7]: This was a tricky one - we don't really know at the compile time if CarPlay is available. So it seems that resorting to runtime checks is the way to go. 

UIKit provides us only with `windowScene`, which is `nil` in case of CarPlay window. `CPWindow` has a separate scene property called `templateApplicationScene`. 
Thus the return value of this computed property will be `windowScene` in case of `UIWindow`, and `templateApplicationScene` in case of `CPWindow`. 

I'm open to suggestions on how to improve this :)

File: Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift [hunk 2]
```diff
@@ -0,0 +1,16 @@
+import UIKit
+
+@available(iOS 13.0, *)
+extension UIWindow {
+    private static let templateApplicationSceneSelector = Selector(("templateApplicationScene"))
+
+    internal var parentScene: UIScene? {
```
Comment (evil159) [inline Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift:7]: This was a tricky one - we don't really know at the compile time if CarPlay is available. So it seems that resorting to runtime checks is the way to go. 

UIKit provides us only with `windowScene`, which is `nil` in case of CarPlay window. `CPWindow` has a separate scene property called `templateApplicationScene`. 
With the help of Objective C runtime we can access here the car play scene(if any).
Thus the return value of this computed property will be `windowScene` in case of `UIWindow`, and `templateApplicationScene` in case of `CPWindow`. 

I'm open to suggestions on how to improve this :)

File: Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+        var carPlayScene: UIScene? {
+            guard self.responds(to: UIWindow.templateApplicationSceneSelector) else {
+                return nil
+            }
+            return self.value(forKey: UIWindow.templateApplicationSceneSelector.description) as? UIScene
+        }
+        return windowScene ?? carPlayScene
+    }
```
Comment (evil159) [inline Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift:15]: This was a tricky one - we don't really know at the compile time if CarPlay is available. So it seems that resorting to runtime checks is the way to go. 

UIKit provides us only with `windowScene`, which is `nil` in case of CarPlay window. `CPWindow` has a separate scene property called `templateApplicationScene`. 
With the help of Objective C runtime we can access here the car play scene(if any).
Thus the return value of this computed property will be `windowScene` in case of `UIWindow`, and `templateApplicationScene` in case of `CPWindow`. 

I'm open to suggestions on how to improve this :)

File: Tests/MapboxMapsTests/Foundation/MapViewTests.swift [hunk 4]
```diff
@@ -187,4 +187,15 @@ final class MapViewTests: XCTestCase {
...
+        mapView.willEnterForeground()
+
+        XCTAssertFalse(displayLink.isPaused)
+    }
+
+    func testDidEnterBackground() {
+        mapView.didEnterBackground()
+
+        XCTAssertTrue(displayLink.isPaused)
+    }
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/MapViewTests.swift:200]: You can stub the isPaused setter to enable verifying that the setter was actually invoked vs. the property just accidentally having the expected value already.

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift [hunk 5]
```diff
@@ -0,0 +1,89 @@
+import Foundation
+import UIKit
+
+@available(iOSApplicationExtension, unavailable)
+extension MapView {
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift:5]: Let's put this in the main MapView implementation so that we can keep more of its interface private.

File: Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift [hunk 6]
```diff
@@ -0,0 +1,16 @@
+import UIKit
+
+@available(iOS 13.0, *)
+extension UIWindow {
+    private static let templateApplicationSceneSelector = Selector(("templateApplicationScene"))
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift:5]: Let's declare constants in the narrowest scope possible. In this case, this can just be a local let constant in carPlayScene.

File: Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift [hunk 7]
```diff
@@ -0,0 +1,16 @@
+import UIKit
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift:1]: Can we rename this file to `UIWindow+ParentScene.swift`

File: Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift (hunk 3 above)
Comment (macdrevx) [reply Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift:15]:
```
    internal var parentScene: UIScene? {
        return windowScene ?? (self as? CPWindow)?.templateApplicationScene
    }
```

Does this work?

Comment (macdrevx) [reply Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift:15]: It's fine to import CarPlay - the framework will be weak-linked automatically if needed based on the deployment target, and we require Xcode 12.5 or later to build, so CarPlay will always be available when linking.

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+    internal func subscribeToMemoryWarningNotification() {
+        NotificationCenter.default.addObserver(self,
+                                               selector: #selector(didReceiveMemoryWarning),
+                                               name: UIApplication.didReceiveMemoryWarningNotification,
+                                               object: nil)
+    }
+
+    internal func subscribeToLifecycleNotifications() {
+        if Bundle.main.object(forInfoDictionaryKey: MapView.UIApplicationSceneManifestKey) != nil {
+            if #available(iOS 13.0, *) {
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift:17]: What happens if there's an app that uses scenes in iOS 13+ and falls back to older tech when running on older iOS versions?

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+
+        switch notification.name {
+        case UIScene.willEnterForegroundNotification:
+            willEnterForeground()
+        case UIScene.didEnterBackgroundNotification:
+            didEnterBackground()
+        default:
+            break
+        }
+    }
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift:65]: Unused?

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+    internal func unsubscribeFromLifecycleNotifications() {
+        if Bundle.main.object(forInfoDictionaryKey: MapView.UIApplicationSceneManifestKey) != nil {
+            if #available(iOS 13.0, *) {
+                NotificationCenter.default.removeObserver(self, name: UIScene.willEnterForegroundNotification, object: nil)
+                NotificationCenter.default.removeObserver(self, name: UIScene.didEnterBackgroundNotification, object: nil)
+            }
+        } else {
+            NotificationCenter.default.removeObserver(self, name: UIApplication.willEnterForegroundNotification, object: nil)
+            NotificationCenter.default.removeObserver(self, name: UIApplication.didEnterBackgroundNotification, object: nil)
+        }
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift:34]: This can be simplified. No need to check for UIApplicationSceneManifestKey. Just unsubscribe from all 4 (or 2 if < iOS 13) every time.

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 11]
```diff
@@ -274,6 +269,8 @@ open class MapView: UIView {
 
         // Set up managers
         setupManagers()
+
+        subscribeToMemoryWarningNotification()
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView.swift:273]: I would revert this change. We only do this once, so it doesn't seem necessary to create a method for it. Just leave it inline as it was before.

**Review by macdrevx — CHANGES_REQUESTED** [review]
Looking good. Can you also make the change to how the display link is initialized?

Tests will need to be more thorough if possible:
* verify notifications are registered/unregistered correctly
* unit test UIWindow.parentScene

File: Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift (hunk 3 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/Extensions/UIWindow.swift]: Good tip, looks much better now!

File: Tests/MapboxMapsTests/Foundation/MapViewTests.swift (hunk 4 above)
Comment (evil159) [reply Tests/MapboxMapsTests/Foundation/MapViewTests.swift]: Stubbed

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift (hunk 5 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift]: Moved it back

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift (hunk 8 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift]: Well spotted! Fixed it.

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift (hunk 9 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift]: 😳

File: Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift (hunk 10 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView+Lifecycle.swift]: Good point, indeed.

File: Sources/MapboxMaps/Foundation/MapView.swift (hunk 11 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView.swift]: Reverted

File: Tests/MapboxMapsTests/Foundation/Mocks/MockNotificationCenter.swift [hunk 12]
```diff
@@ -0,0 +1,36 @@
+import Foundation
+@testable import MapboxMaps
+
+final class MockNotificationCenter: NotificationCenterProtocol {
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/Mocks/MockNotificationCenter.swift:4]: Is it worth it to mock notification center? NotificationCenter.default delivers notifications synchronously already, and if we verify that the expected behaviors happen when a notification is posted, we'll know that the observer was added correctly.

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 13]
```diff
@@ -164,7 +167,7 @@ open class MapView: UIView {
     }
 
     deinit {
-        NotificationCenter.default.removeObserver(self)
+        notificationCenter.removeObserver(self)
     }
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView.swift:171]: We should just delete this. NotificationCenter keeps weak refs to observers on every OS version we support.

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 14]
```diff
@@ -326,6 +335,74 @@ open class MapView: UIView {
             mapboxMap: mapboxMap)
     }
 
+    private func subscribeToLifecycleNotifications() {
+        if bundle.infoDictionary?["UIApplicationSceneManifest"] != nil {
+            if #available(iOS 13.0, *) {
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView.swift:340]: You can combine these into a single if statement and avoid the duplication in the else blocks.

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 15]
```diff
@@ -326,6 +335,74 @@ open class MapView: UIView {
...
+    private func unsubscribeFromLifecycleNotifications() {
+        if #available(iOS 13.0, *) {
+            notificationCenter.removeObserver(self, name: UIScene.willEnterForegroundNotification, object: nil)
+            notificationCenter.removeObserver(self, name: UIScene.didEnterBackgroundNotification, object: nil)
+        }
+        notificationCenter.removeObserver(self, name: UIApplication.willEnterForegroundNotification, object: nil)
+        notificationCenter.removeObserver(self, name: UIApplication.didEnterBackgroundNotification, object: nil)
+    }
+
+    @objc private func didReceiveNotification(_ notification: Notification) {
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView.swift:380]: Can we name this more specifically?

Comment (macdrevx) [reply Sources/MapboxMaps/Foundation/MapView.swift:380]: Hmm, I guess I'm saying I'd rather have separate 3 separate handlers for foreground, background, and memory warnings.

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 16]
```diff
@@ -430,7 +507,9 @@ open class MapView: UIView {
 
         if window != nil {
             validateDisplayLink()
+            subscribeToLifecycleNotifications()
         } else {
+            unsubscribeFromLifecycleNotifications()
             // TODO: Fix this up correctly.
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView.swift:513]: You're going to have conflicts with your other PR. Do you have a preference which one to merge first?

File: Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift [hunk 17]
```diff
@@ -0,0 +1,20 @@
...
+import CarPlay
+@testable import MapboxMaps
+
+final class UIWindowParentSizeTests: XCTestCase {
+
+    @available(iOS 13.0, *)
+    func testCarPlayWindowReturnsCorrectParentScene() {
+        let window = CPWindow()
+
+        XCTAssertEqual(window.parentScene, window.templateApplicationScene)
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:11]: What are the actual values? Are they both nil? If so, that might not be a very good test.

File: Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift [hunk 18]
```diff
@@ -0,0 +1,20 @@
...
+    }
+
+    @available(iOS 13.0, *)
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:14]: Please make sure the tests pass on OS versions < 13

Comment (macdrevx) [reply Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:14]: I vaguely recall this not working in tests and needing to do runtime checks in the test implementation.

Comment (macdrevx) [reply Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:14]: But test it to make sure I'm not misremembering.

File: Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift [hunk 19]
```diff
@@ -0,0 +1,20 @@
...
+    func testUIWindowReturnsCorrectParentScene() {
+        let window = UIWindow()
+
+        XCTAssertEqual(window.parentScene, window.windowScene)
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:18]: Same question here about the actual values.

File: Tests/MapboxMapsTests/Foundation/MapViewTests.swift [hunk 20]
```diff
@@ -4,6 +4,8 @@ import XCTest
 final class MapViewTests: XCTestCase {
 
     var displayLink: MockDisplayLink!
+    var notificationCenter: MockNotificationCenter!
+    var bundle: MockBundle!
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/MapViewTests.swift:8]: Please nil these in tearDown

File: Tests/MapboxMapsTests/Foundation/MapViewTests.swift [hunk 21]
```diff
@@ -182,9 +188,113 @@ final class MapViewTests: XCTestCase {
...
+        let bundle = MockBundle()
+        bundle.infoDictionaryStub.defaultReturnValue = [:]
+        dependencyProvider.makeNotificationCenterStub.defaultReturnValue = notificationCenter
+        dependencyProvider.makeBundleStub.defaultReturnValue = bundle
+        let mapView = MapView(
+            frame: CGRect(origin: .zero, size: CGSize(width: 100, height: 100)),
+            mapInitOptions: MapInitOptions(),
+            dependencyProvider: dependencyProvider)
+
+        window.addSubview(mapView)
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/MapViewTests.swift:202]: Is this necessary? seems to duplicate what's already happening in setUp

Comment (macdrevx) [reply Tests/MapboxMapsTests/Foundation/MapViewTests.swift:202]: Similarly in the other tests.

File: Tests/MapboxMapsTests/Foundation/MapViewTests.swift [hunk 22]
```diff
@@ -182,9 +188,113 @@ final class MapViewTests: XCTestCase {
...
+
+        XCTAssertTrue(notificationCenter.addObserverStub.invocations.contains(where: { stub in
+            stub.parameters.name == UIApplication.didEnterBackgroundNotification
+        }))
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/MapViewTests.swift:206]: I'd name these arguments `invocation` instead of `stub` to match the type.

File: Tests/MapboxMapsTests/Foundation/MapViewTests.swift [hunk 23]
```diff
@@ -182,9 +188,113 @@ final class MapViewTests: XCTestCase {
...
+            dependencyProvider: dependencyProvider)
+
+        window.addSubview(mapView)
+
+        XCTAssertTrue(notificationCenter.addObserverStub.invocations.contains(where: { stub in
+            stub.parameters.name == UIScene.didEnterBackgroundNotification
+        }))
+        XCTAssertTrue(notificationCenter.addObserverStub.invocations.contains(where: { stub in
+            stub.parameters.name == UIScene.willEnterForegroundNotification
+        }))
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/MapViewTests.swift:235]: We need to verify the `object` as well as the `name` here since an app may contain multiple scenes.

File: Tests/MapboxMapsTests/Foundation/MapViewTests.swift [hunk 24]
```diff
@@ -182,9 +188,113 @@ final class MapViewTests: XCTestCase {
...
+
+        XCTAssertEqual(displayLink.$isPaused.setStub.parameters, [false])
     }
 
+    @available(iOS 13.0, *)
+    func testDisplayLinkResumedWhenSceneMovingToForeground() {
+        bundle.infoDictionaryStub.defaultReturnValue = ["UIApplicationSceneManifest": []]
+        mapView.didMoveToWindow()
+
+        notificationCenter.post(name: UIScene.willEnterForegroundNotification, object: window.parentScene)
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/MapViewTests.swift:286]: Is parentScene nil?

**Review by macdrevx — COMMENTED** [review]
Still on the right track! Let me know if you want to talk through any of the feedback.

File: Tests/MapboxMapsTests/Foundation/Mocks/MockNotificationCenter.swift (hunk 12 above)
Comment (evil159) [reply Tests/MapboxMapsTests/Foundation/Mocks/MockNotificationCenter.swift:4]: I think the advantage of Mocking Notification Center is in that allows us to directly verify when subscription/unsubscription happens, instead of relying on indirects signs.

File: Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift (hunk 19 above)
Comment (evil159) [reply Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:18]: `windowScene` seems to be a special property as it gets populated even when creating a window directly. So in this case bot `parentScene` and `windowScene` won't be nil.

File: Sources/MapboxMaps/Foundation/MapView.swift (hunk 16 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView.swift:513]: This one for sure, the other PR is smaller and should be easier to resolve conflicts in.

File: Sources/MapboxMaps/Foundation/MapView.swift (hunk 14 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView.swift:340]: TIL 😲

File: Sources/MapboxMaps/Foundation/MapView.swift (hunk 13 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView.swift:171]: Deleted.

File: Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift (hunk 18 above)
Comment (evil159) [reply Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift]: Good point, indeed it just crashes when running e.g. on iOS 12 with these annotations. Converted them to runtime checks.

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 25]
```diff
@@ -326,6 +331,64 @@ open class MapView: UIView {
...
+        displayLink?.isPaused = false
+    }
+
+    @objc private func appDidEnterBackground() {
+        displayLink?.isPaused = true
+    }
+
+    @available(iOS 13.0, *)
+    @objc private func sceneWillEnterForeground(_ notification: Notification) {
+        guard notification.object as? UIScene == window?.parentScene else { return }
```
Comment (macdrevx) [inline Sources/MapboxMaps/Foundation/MapView.swift:375]: I don't think these checks are necessary since we only subscribe for a specific object.

Comment (macdrevx) [reply Sources/MapboxMaps/Foundation/MapView.swift:375]: Removing them would allow you to share handlers with the app lifecycle notifications

Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView.swift:375]: I added them here to protect against a situation when map view moves to a window without scene attached(there is no clear documentation on specifics of this). So map view will subscribe to lifecycle notifications with `nil` object. And this supposed to be a safeguard against it.

File: Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift (hunk 17 above)
Comment (macdrevx) [reply Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:13]: Not for this PR, but I wonder whether we could set up a test suite that runs in a host app with CarPlay entitlements.

File: Sources/MapboxMaps/Foundation/MapView.swift (hunk 25 above)
Comment (macdrevx) [reply Sources/MapboxMaps/Foundation/MapView.swift:375]: So the scenario is, on iOS 13+ with scenes enabled, map view moves to a window that has a nil scene?

In that case, we would basically not get pausing and resuming until the window's scene became non-nil, right?

Not sure if this scenario is even possible.

**Review by macdrevx — APPROVED** [review]
Approving, but can you take care of one more thing before merging? https://github.com/mapbox/mapbox-maps-ios/pull/1086#discussion_r801762176

File: Sources/MapboxMaps/Foundation/MapView.swift (hunk 25 above)
Comment (evil159) [reply Sources/MapboxMaps/Foundation/MapView.swift:375]: Yeah, in this scenario we won't get pausing and resuming, it either this or pausing and resuming by notifications from a random scene(if there would be no checks). But this scenario is definitely in the realm of possibility - windowScene is optional readwrite property.

File: Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift (hunk 17 above)
Comment (evil159) [reply Tests/MapboxMapsTests/Foundation/Extensions/UIWindow+ParentSceneTests.swift:13]: Good point, this will enable for tests like this to be run properly, let's get back to it next time we touch CarPlay related stuff.

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 26]
```diff
@@ -326,6 +331,64 @@ open class MapView: UIView {
...
+                                           object: window?.parentScene)
+            notificationCenter.addObserver(self,
+                                           selector: #selector(sceneDidEnterBackground(_:)),
+                                           name: UIScene.didEnterBackgroundNotification,
+                                           object: window?.parentScene)
+        } else {
+            notificationCenter.addObserver(self,
+                                           selector: #selector(appWillEnterForeground),
+                                           name: UIApplication.willEnterForegroundNotification,
+                                           object: nil)
```
Comment (1ec5) [inline Sources/MapboxMaps/Foundation/MapView.swift:348]: Per mapbox/mapbox-gl-native#1869, this may be too early for mbgl to wake up and start rendering again:

> UIApplicationWillEnterForegroundNotification is posted before UIApplicationDidBecomeActiveNotification, while the application is still in the background.

/ref mapbox/mapbox-gl-native#1821

File: Sources/MapboxMaps/Foundation/MapView.swift [hunk 27]
```diff
@@ -326,6 +331,64 @@ open class MapView: UIView {
             mapboxMap: mapboxMap)
     }
 
+    private func subscribeToLifecycleNotifications() {
+        if #available(iOS 13.0, *), bundle.infoDictionary?["UIApplicationSceneManifest"] != nil {
+            notificationCenter.addObserver(self,
+                                           selector: #selector(sceneWillEnterForeground(_:)),
+                                           name: UIScene.willEnterForegroundNotification,
+                                           object: window?.parentScene)
```
Comment (1ec5) [inline Sources/MapboxMaps/Foundation/MapView.swift:339]: As with `UIApplication.willEnterForegroundNotification`, `UIScene.willEnterForegroundNotification` is probably premature as well. `UIScene.didActivateNotification` would be more reliable.

Comment (1ec5) [reply Sources/MapboxMaps/Foundation/MapView.swift:339]: #1402 replaces this with `UIApplication.didBecomeActiveNotification`.

File: Sources/MapboxMaps/Foundation/MapView.swift (hunk 26 above)
Comment (1ec5) [reply Sources/MapboxMaps/Foundation/MapView.swift:348]: #1402 replaces this with `UIScene.didActivateNotification`.
